import React from "react";

const Home: React.FC = () => {
  return (
  <>
  <div>
    <h1>Article</h1>
    </div>
  <div>
    <h1>Article</h1>
    </div>
  <div>
    <h1>Article</h1>
    </div>
  <div>
    <h1>Article</h1>
    </div>
  <div>
    <h1>Article</h1>
    </div>
  <div>
    <h1>Article</h1>
    </div>
  <div>
    <h1>Article</h1>
    </div>
  <div>
    <h1>Article</h1>
    </div>
  <div>
    <h1>Article</h1>
    </div>
  <div>
    <h1>Article</h1>
    </div>
  <div>
    <h1>Article</h1>
    </div>
  <div>
    <h1>Article</h1>
    </div>
  <div>
    <h1>Article</h1>
    </div>
  <div>
    <h1>Article</h1>
    </div>
  <div>
    <h1>Article</h1>
    </div>
  <div>
    <h1>Article</h1>
    </div>
  <div>
    <h1>Article</h1>
    </div>
  <div>
    <h1>Article</h1>
    </div>
  <div>
    <h1>Article</h1>
    </div>
  <div>
    <h1>Article</h1>
    </div>
  <div>
    <h1>Article</h1>
    </div>
  <div>
    <h1>Article</h1>
    </div>
  <div>
    <h1>Article</h1>
    </div>
  <div>
    <h1>Article</h1>
    </div>
  </>
  );
}

export default Home;